<?php
return [
    'language_name' => 'العربية',
    'common' => ['home' => 'الرئيسية','profile' => 'الملف الشخصي','appointments' => 'المواعيد','payments' => 'المدفوعات والفواتير','reports' => 'التقارير / المستندات','notifications' => 'الإشعارات','messages' => 'الرسائل / الدردشة','consultations' => 'الاستشارة المرئية','scanner' => 'ماسح الذكاء الاصطناعي','map' => 'الخريطة التفاعلية','guidelines' => 'الإرشادات والمساعدة','faq' => 'الأسئلة الشائعة','verification' => 'مركز التحقق','templates' => 'قوالب البريد والرسائل','logout' => 'تسجيل الخروج','sign_in' => 'تسجيل الدخول','dashboard' => 'لوحة التحكم','guest' => 'زائر','public' => 'عام','view_all' => 'عرض الكل','back' => 'رجوع','search_placeholder' => 'ابحث عن الأطباء أو المستشفيات أو التقارير...','mark_all_read' => 'تحديد الكل كمقروء','save_preferences' => 'حفظ التفضيلات','language' => 'اللغة','subscribe' => 'اشتراك','get_started' => 'ابدأ الآن','find_healthcare' => 'ابحث عن الرعاية الصحية'],
    'layout' => ['about_title' => 'حول ميديسفير','about_text' => 'منصة رعاية صحية احترافية للمرضى والأطباء والمستشفيات والإدارة.','footer_note' => 'مبنية لـ XAMPP + PHP 8 + MySQL.','notifications_title' => 'الإشعارات','no_notifications' => 'لا توجد إشعارات بعد.','assistant_title' => 'المساعد الصحي','assistant_subtitle' => 'اسأل عن المواعيد والتقارير والدعم','quick_book' => 'كيف أحجز موعدًا؟','quick_reports' => 'كيف أرفع التقارير؟','quick_emergency' => 'إجراءات الطوارئ؟'],
    'home' => ['eyebrow' => 'نظام رعاية صحية آمن ومتعدد البوابات مدعوم بالذكاء الاصطناعي','title' => 'إدارة رعاية صحية متميزة للمرضى والأطباء والمستشفيات وفرق الإدارة.','subtitle' => 'احجز المواعيد وافحص الصور الطبية ونظّم التقارير والاستشارات في منصة واحدة حديثة.','features_eyebrow' => 'ميزات المنصة','features_title' => 'مصممة لدعم رحلة الرعاية الكاملة','how_it_works' => 'كيف تعمل','how_title' => 'رحلة رعاية رقمية سهلة من 3 خطوات','featured_doctors' => 'أطباء مميزون','trusted_specialists' => 'متخصصون موثوقون','partner_hospitals' => 'المستشفيات الشريكة','global_directory' => 'دليل مستشفيات عالمي','content_eyebrow' => 'محتوى صحي','content_title' => 'المدونة والإرشادات وتثقيف المرضى','newsletter_eyebrow' => 'ابقَ على اطلاع','newsletter_title' => 'الاشتراك بالنشرة','newsletter_placeholder' => 'أدخل بريدك الإلكتروني','newsletter_note' => 'يمكن ربط هذا القسم بأي خدمة نشرات بريدية.','snapshot' => 'لقطة صحية','live' => 'مباشر','upcoming' => 'المواعيد القادمة','ai_scans' => 'فحوصات الذكاء الاصطناعي','verified_doctors' => 'أطباء موثقون','hospital_partners' => 'مستشفيات شريكة','smart_triage' => 'فرز ذكي','scanner_title' => 'ماسح الأمراض بالذكاء الاصطناعي','scanner_text' => 'ارفع صور الجلد أو العين أو الأشعة واربط النتائج بالحجز والتقارير.','testimonial' => 'ميديسفير يقلل التعقيد التشغيلي ويجعل رحلة الرعاية أكثر سلاسة.','metrics' => ['specializations' => 'التخصصات','support' => 'قنوات الدعم','security' => 'هيكل جاهز للأمان'],'features' => require __DIR__ . '/partials/en_home_features.php','steps' => require __DIR__ . '/partials/en_home_steps.php','blogs' => ['كيف يدعم الذكاء الاصطناعي الفحص','الخصوصية وHIPAA والطب عن بعد الآمن','أفضل ممارسات إدارة المواعيد الرقمية']],
    'auth' => ['eyebrow' => 'وصول آمن','title' => 'الوصول إلى منظومة الرعاية الخاصة بك','subtitle' => 'أنشئ حساب مريض أو طبيب أو مستشفى.','login' => 'تسجيل الدخول','patient_register' => 'تسجيل مريض','doctor_register' => 'تسجيل طبيب','hospital_register' => 'تسجيل مستشفى','forgot_password' => 'هل نسيت كلمة المرور؟','or_continue' => 'أو تابع عبر','send_reset' => 'إرسال رابط إعادة التعيين','reset_title' => 'إعادة تعيين كلمة المرور'],
    'faq' => ['eyebrow' => 'مركز الدعم','title' => 'الأسئلة الشائعة','subtitle' => 'أسئلة قابلة للبحث مع إجابات قابلة للتوسيع.'],
    'guidelines' => ['eyebrow' => 'الإرشادات','title' => 'إرشادات استخدام المنصة'],
    'notifications' => ['eyebrow' => 'مركز الإشعارات','title' => 'الإشعارات','recent' => 'الإشعارات الأخيرة','preferences' => 'التفضيلات','unread' => 'غير مقروء'],
    'consultations' => ['eyebrow' => 'الطب عن بُعد','title' => 'الاستشارة المرئية','waiting_queue' => 'قائمة الانتظار','eligible' => 'المواعيد المؤهلة','call_history' => 'سجل المكالمات','room_overview' => 'نظرة عامة على الجلسة','waiting_room' => 'غرفة انتظار افتراضية','connection_events' => 'أحداث الاتصال','feedback' => 'تقييم الاستشارة'],
    'chatbot' => ['book_answer' => 'اذهب إلى صفحة المواعيد واختر الطبيب والتاريخ والوقت ثم أرسل الأعراض.','reports_answer' => 'افتح صفحة التقارير، اختر التصنيف وارفع الملف ثم احفظه.','emergency_answer' => 'في الحالات العاجلة اتصل بخدمات الطوارئ المحلية فورًا.'],
];
