<?php
return [
    'language_name' => 'Deutsch',
    'common' => ['home' => 'Startseite','profile' => 'Profil','appointments' => 'Termine','payments' => 'Zahlungen & Rechnungen','reports' => 'Berichte / Dokumente','notifications' => 'Benachrichtigungen','messages' => 'Nachrichten / Chat','consultations' => 'Videosprechstunde','scanner' => 'KI-Scanner','map' => 'Interaktive Karte','guidelines' => 'Leitfäden & Hilfe','faq' => 'FAQ','verification' => 'Verifizierungszentrum','templates' => 'E-Mail- & SMS-Vorlagen','logout' => 'Abmelden','sign_in' => 'Anmelden','dashboard' => 'Dashboard','guest' => 'Gast','public' => 'Öffentlich','view_all' => 'Alle ansehen','back' => 'Zurück','search_placeholder' => 'Ärzte, Krankenhäuser, Berichte suchen...','mark_all_read' => 'Alle als gelesen markieren','save_preferences' => 'Einstellungen speichern','language' => 'Sprache','subscribe' => 'Abonnieren','get_started' => 'Loslegen','find_healthcare' => 'Gesundheitsdienste finden'],
    'layout' => ['about_title' => 'Über MediSphere','about_text' => 'Premium-Plattform für das Gesundheitsmanagement von Patienten, Ärzten, Krankenhäusern und Administratoren.','footer_note' => 'Erstellt für XAMPP + PHP 8 + MySQL.','notifications_title' => 'Benachrichtigungen','no_notifications' => 'Noch keine Benachrichtigungen.','assistant_title' => 'Gesundheitsassistent','assistant_subtitle' => 'Fragen Sie nach Terminen, Berichten und Support','quick_book' => 'Wie buche ich einen Termin?','quick_reports' => 'Wie lade ich Berichte hoch?','quick_emergency' => 'Notfallverfahren?'],
    'home' => ['eyebrow' => 'KI-gestütztes, sicheres Gesundheitsökosystem mit mehreren Portalen','title' => 'Premium-Gesundheitsmanagement für Patienten, Ärzte, Krankenhäuser und Admin-Teams.','subtitle' => 'Buchen Sie Termine, scannen Sie medizinische Bilder, verwalten Sie Berichte und koordinieren Sie Konsultationen über eine moderne Plattform.','features_eyebrow' => 'Plattformfunktionen','features_title' => 'Für die komplette Versorgungskette entwickelt','how_it_works' => 'So funktioniert es','how_title' => 'Einfacher digitaler 3-Schritte-Ablauf','featured_doctors' => 'Empfohlene Ärzte','trusted_specialists' => 'Vertrauenswürdige Spezialisten','partner_hospitals' => 'Partnerkrankenhäuser','global_directory' => 'Globales Krankenhausverzeichnis','content_eyebrow' => 'Gesundheitsinhalte','content_title' => 'Blog, Leitfäden und Patientenbildung','newsletter_eyebrow' => 'Bleiben Sie informiert','newsletter_title' => 'Newsletter-Anmeldung','newsletter_placeholder' => 'E-Mail eingeben','newsletter_note' => 'Verbinden Sie diesen Bereich mit Ihrer bevorzugten Newsletter-API.','snapshot' => 'Gesundheitsüberblick','live' => 'Live','upcoming' => 'Bevorstehende Termine','ai_scans' => 'KI-Scans','verified_doctors' => 'Verifizierte Ärzte','hospital_partners' => 'Krankenhauspartner','smart_triage' => 'Intelligente Triage','scanner_title' => 'KI-Krankheitsscanner','scanner_text' => 'Laden Sie Haut-, Augen- oder Röntgenbilder hoch und verknüpfen Sie die Ergebnisse mit Buchungen und Berichten.','testimonial' => 'MediSphere reduziert operative Komplexität und hält den Versorgungspfad intuitiv und sicher.','metrics' => ['specializations' => 'Fachrichtungen','support' => 'Supportkanäle','security' => 'Sicherheitsbereite Grundlage'],'features' => require __DIR__ . '/partials/en_home_features.php','steps' => require __DIR__ . '/partials/en_home_steps.php','blogs' => ['Wie KI Screening unterstützt','Datenschutz, HIPAA und sichere Telemedizin','Best Practices für digitale Terminverwaltung']],
    'auth' => ['eyebrow' => 'Sicherer Zugang','title' => 'Zugriff auf Ihr Versorgungssystem','subtitle' => 'Erstellen Sie ein Patienten-, Arzt- oder Krankenhauskonto.','login' => 'Anmelden','patient_register' => 'Patient registrieren','doctor_register' => 'Arzt registrieren','hospital_register' => 'Krankenhaus registrieren','forgot_password' => 'Passwort vergessen?','or_continue' => 'Oder fortfahren mit','send_reset' => 'Reset-Link senden','reset_title' => 'Passwort zurücksetzen'],
    'faq' => ['eyebrow' => 'Support-Center','title' => 'Häufig gestellte Fragen','subtitle' => 'Durchsuchbare FAQ mit aufklappbaren Antworten.'],
    'guidelines' => ['eyebrow' => 'Leitfäden','title' => 'Nutzungsleitfäden der Plattform'],
    'notifications' => ['eyebrow' => 'Benachrichtigungszentrum','title' => 'Benachrichtigungen','recent' => 'Neueste Benachrichtigungen','preferences' => 'Einstellungen','unread' => 'Ungelesen'],
    'consultations' => ['eyebrow' => 'Telemedizin','title' => 'Videosprechstunde','waiting_queue' => 'Warteschlange','eligible' => 'Verfügbare Termine','call_history' => 'Anrufverlauf','room_overview' => 'Sitzungsübersicht','waiting_room' => 'Virtueller Warteraum','connection_events' => 'Verbindungsereignisse','feedback' => 'Feedback zur Sprechstunde'],
    'chatbot' => ['book_answer' => 'Gehen Sie zu Termine, wählen Sie Arzt, Datum und Uhrzeit und senden Sie Ihre Symptome.','reports_answer' => 'Öffnen Sie Berichte, wählen Sie eine Kategorie, laden Sie Ihre Datei hoch und speichern Sie sie.','emergency_answer' => 'Im Notfall sofort die lokalen Rettungsdienste kontaktieren.'],
];
