<?php
return [
    'language_name' => 'Español',
    'common' => ['home' => 'Inicio','profile' => 'Perfil','appointments' => 'Citas','payments' => 'Pagos y facturas','reports' => 'Reportes / documentos','notifications' => 'Notificaciones','messages' => 'Mensajes / chat','consultations' => 'Consulta por video','scanner' => 'Escáner IA','map' => 'Mapa interactivo','guidelines' => 'Guías y ayuda','faq' => 'Preguntas frecuentes','verification' => 'Centro de verificación','templates' => 'Plantillas de correo y SMS','logout' => 'Cerrar sesión','sign_in' => 'Iniciar sesión','dashboard' => 'Panel','guest' => 'Invitado','public' => 'Público','view_all' => 'Ver todo','back' => 'Volver','search_placeholder' => 'Buscar doctores, hospitales, reportes...','mark_all_read' => 'Marcar todo como leído','save_preferences' => 'Guardar preferencias','language' => 'Idioma','subscribe' => 'Suscribirse','get_started' => 'Comenzar','find_healthcare' => 'Buscar atención médica'],
    'layout' => ['about_title' => 'Sobre MediSphere','about_text' => 'Plataforma premium de gestión sanitaria para pacientes, doctores, hospitales y administradores.','footer_note' => 'Construido para XAMPP + PHP 8 + MySQL.','notifications_title' => 'Notificaciones','no_notifications' => 'Aún no hay notificaciones.','assistant_title' => 'Asistente de salud','assistant_subtitle' => 'Pregunta sobre citas, reportes y soporte','quick_book' => '¿Cómo reservar una cita?','quick_reports' => '¿Cómo subir reportes?','quick_emergency' => '¿Procedimientos de emergencia?'],
    'home' => ['eyebrow' => 'Ecosistema de salud seguro y multportal impulsado por IA','title' => 'Gestión sanitaria premium para pacientes, doctores, hospitales y equipos administrativos.','subtitle' => 'Reserve citas, analice imágenes médicas, administre reportes y coordine consultas desde una sola plataforma moderna.','features_eyebrow' => 'Funciones de la plataforma','features_title' => 'Diseñada para apoyar todo el recorrido asistencial','how_it_works' => 'Cómo funciona','how_title' => 'Flujo digital de atención en 3 pasos','featured_doctors' => 'Doctores destacados','trusted_specialists' => 'Especialistas confiables','partner_hospitals' => 'Hospitales asociados','global_directory' => 'Directorio hospitalario global','content_eyebrow' => 'Contenido de salud','content_title' => 'Blog, guías y educación del paciente','newsletter_eyebrow' => 'Mantente informado','newsletter_title' => 'Suscripción al boletín','newsletter_placeholder' => 'Introduce tu correo','newsletter_note' => 'Conecta esta área con tu API de boletines favorita.','snapshot' => 'Resumen de salud','live' => 'En vivo','upcoming' => 'Próximas citas','ai_scans' => 'Escaneos IA','verified_doctors' => 'Doctores verificados','hospital_partners' => 'Hospitales asociados','smart_triage' => 'Triage inteligente','scanner_title' => 'Escáner de enfermedades con IA','scanner_text' => 'Sube imágenes de piel, ojos o rayos X y conecta los resultados con citas y reportes.','testimonial' => 'MediSphere reduce la complejidad operativa y mantiene la atención intuitiva y segura.','metrics' => ['specializations' => 'Especialidades','support' => 'Canales de soporte','security' => 'Base lista para seguridad'],'features' => require __DIR__ . '/partials/en_home_features.php','steps' => require __DIR__ . '/partials/en_home_steps.php','blogs' => ['Cómo la IA apoya el cribado','Privacidad, HIPAA y telemedicina segura','Buenas prácticas para gestionar citas digitales']],
    'auth' => ['eyebrow' => 'Acceso seguro','title' => 'Accede a tu ecosistema de atención','subtitle' => 'Crea una cuenta de paciente, doctor u hospital.','login' => 'Iniciar sesión','patient_register' => 'Registro de paciente','doctor_register' => 'Registro de doctor','hospital_register' => 'Registro de hospital','forgot_password' => '¿Olvidaste tu contraseña?','or_continue' => 'O continúa con','send_reset' => 'Enviar enlace de restablecimiento','reset_title' => 'Restablecer contraseña'],
    'faq' => ['eyebrow' => 'Centro de soporte','title' => 'Preguntas frecuentes','subtitle' => 'Preguntas buscables con respuestas expandibles.'],
    'guidelines' => ['eyebrow' => 'Guías','title' => 'Guías de uso de la plataforma'],
    'notifications' => ['eyebrow' => 'Centro de notificaciones','title' => 'Notificaciones','recent' => 'Notificaciones recientes','preferences' => 'Preferencias','unread' => 'No leídas'],
    'consultations' => ['eyebrow' => 'Telemedicina','title' => 'Consulta por video','waiting_queue' => 'Sala de espera','eligible' => 'Citas elegibles','call_history' => 'Historial de llamadas','room_overview' => 'Resumen de sesión','waiting_room' => 'Sala de espera virtual','connection_events' => 'Eventos de conexión','feedback' => 'Opinión de la consulta'],
    'chatbot' => ['book_answer' => 'Ve a Citas, elige doctor, fecha y hora y envía tus síntomas.','reports_answer' => 'Abre Reportes, elige categoría, sube tu archivo y guárdalo.','emergency_answer' => 'En una urgencia llama de inmediato a los servicios de emergencia locales.'],
];
