<?php
return [
    'language_name' => 'Français',
    'common' => ['home' => 'Accueil','profile' => 'Profil','appointments' => 'Rendez-vous','payments' => 'Paiements et factures','reports' => 'Rapports / documents','notifications' => 'Notifications','messages' => 'Messages / chat','consultations' => 'Consultation vidéo','scanner' => 'Scanner IA','map' => 'Carte interactive','guidelines' => 'Guides et aide','faq' => 'FAQ','verification' => 'Centre de vérification','templates' => 'Modèles e-mail et SMS','logout' => 'Déconnexion','sign_in' => 'Connexion','dashboard' => 'Tableau de bord','guest' => 'Invité','public' => 'Public','view_all' => 'Voir tout','back' => 'Retour','search_placeholder' => 'Rechercher des médecins, hôpitaux, rapports...','mark_all_read' => 'Tout marquer comme lu','save_preferences' => 'Enregistrer les préférences','language' => 'Langue','subscribe' => "S'abonner",'get_started' => 'Commencer','find_healthcare' => 'Trouver des soins'],
    'layout' => ['about_title' => 'À propos de MediSphere','about_text' => 'Plateforme premium de gestion de santé pour patients, médecins, hôpitaux et administrateurs.','footer_note' => 'Conçu pour XAMPP + PHP 8 + MySQL.','notifications_title' => 'Notifications','no_notifications' => 'Aucune notification pour le moment.','assistant_title' => 'Assistant santé','assistant_subtitle' => 'Posez des questions sur les rendez-vous, rapports et le support','quick_book' => 'Comment prendre un rendez-vous ?','quick_reports' => 'Comment téléverser des rapports ?','quick_emergency' => "Procédures d'urgence ?"],
    'home' => ['eyebrow' => 'Écosystème de santé sécurisé et multi-portail alimenté par l’IA','title' => 'Gestion de santé premium pour patients, médecins, hôpitaux et équipes administratives.','subtitle' => 'Réservez des rendez-vous, analysez des images médicales, gérez les rapports et coordonnez les consultations depuis une seule plateforme moderne.','features_eyebrow' => 'Fonctionnalités de la plateforme','features_title' => 'Conçue pour accompagner tout le parcours de soin','how_it_works' => 'Comment ça marche','how_title' => 'Parcours numérique de soin en 3 étapes','featured_doctors' => 'Médecins à la une','trusted_specialists' => 'Spécialistes de confiance','partner_hospitals' => 'Hôpitaux partenaires','global_directory' => 'Annuaire hospitalier mondial','content_eyebrow' => 'Contenu santé','content_title' => 'Blog, guides et éducation du patient','newsletter_eyebrow' => 'Restez informé','newsletter_title' => 'Inscription à la newsletter','newsletter_placeholder' => 'Entrez votre e-mail','newsletter_note' => 'Connectez cette zone à votre API newsletter préférée.','snapshot' => 'Vue santé','live' => 'En direct','upcoming' => 'Rendez-vous à venir','ai_scans' => 'Scans IA','verified_doctors' => 'Médecins vérifiés','hospital_partners' => 'Hôpitaux partenaires','smart_triage' => 'Triage intelligent','scanner_title' => 'Scanner de maladies IA','scanner_text' => 'Téléversez des images de peau, yeux ou radiographies et reliez les résultats aux rendez-vous.','testimonial' => 'MediSphere réduit la complexité opérationnelle tout en gardant le parcours patient intuitif et sûr.','metrics' => ['specializations' => 'Spécialités','support' => 'Canaux de support','security' => 'Structure prête pour la sécurité'],'features' => require __DIR__ . '/partials/en_home_features.php','steps' => require __DIR__ . '/partials/en_home_steps.php','blogs' => ["Comment l'IA soutient le dépistage",'Confidentialité, HIPAA et télémédecine sécurisée','Bonnes pratiques de gestion des rendez-vous numériques']],
    'auth' => ['eyebrow' => 'Accès sécurisé','title' => 'Accédez à votre écosystème de soins','subtitle' => 'Créez un compte patient, médecin ou hôpital.','login' => 'Connexion','patient_register' => 'Inscription patient','doctor_register' => 'Inscription médecin','hospital_register' => 'Inscription hôpital','forgot_password' => 'Mot de passe oublié ?','or_continue' => 'Ou continuer avec','send_reset' => 'Envoyer le lien de réinitialisation','reset_title' => 'Réinitialiser votre mot de passe'],
    'faq' => ['eyebrow' => 'Centre de support','title' => 'Questions fréquentes','subtitle' => 'FAQ consultable avec réponses dépliables.'],
    'guidelines' => ['eyebrow' => 'Guides','title' => 'Guides d’utilisation de la plateforme'],
    'notifications' => ['eyebrow' => 'Centre de notifications','title' => 'Notifications','recent' => 'Notifications récentes','preferences' => 'Préférences','unread' => 'Non lues'],
    'consultations' => ['eyebrow' => 'Télémédecine','title' => 'Consultation vidéo','waiting_queue' => "Salle d'attente",'eligible' => 'Rendez-vous éligibles','call_history' => 'Historique des appels','room_overview' => 'Aperçu de session','waiting_room' => "Salle d'attente virtuelle",'connection_events' => 'Événements de connexion','feedback' => 'Avis de consultation'],
    'chatbot' => ['book_answer' => 'Allez dans Rendez-vous, choisissez le médecin, la date et l’heure puis envoyez vos symptômes.','reports_answer' => 'Ouvrez Rapports, choisissez une catégorie, téléversez votre fichier et enregistrez-le.','emergency_answer' => "En cas d'urgence, contactez immédiatement les services d'urgence locaux."],
];
