<?php
return [
    'language_name' => 'हिन्दी',
    'common' => ['home' => 'होम','profile' => 'प्रोफ़ाइल','appointments' => 'अपॉइंटमेंट','payments' => 'भुगतान और इनवॉइस','reports' => 'रिपोर्ट / दस्तावेज़','notifications' => 'नोटिफिकेशन','messages' => 'मैसेज / चैट','consultations' => 'वीडियो परामर्श','scanner' => 'एआई स्कैनर','map' => 'इंटरैक्टिव मैप','guidelines' => 'गाइडलाइन और सहायता','faq' => 'अक्सर पूछे जाने वाले सवाल','verification' => 'वेरिफिकेशन सेंटर','templates' => 'ईमेल और एसएमएस टेम्पलेट','logout' => 'लॉग आउट','sign_in' => 'साइन इन','dashboard' => 'डैशबोर्ड','guest' => 'अतिथि','public' => 'पब्लिक','view_all' => 'सभी देखें','back' => 'वापस','search_placeholder' => 'डॉक्टर, अस्पताल, रिपोर्ट खोजें...','mark_all_read' => 'सभी को पढ़ा हुआ चिह्नित करें','save_preferences' => 'पसंद सहेजें','language' => 'भाषा','subscribe' => 'सब्सक्राइब करें','get_started' => 'शुरू करें','find_healthcare' => 'हेल्थकेयर खोजें'],
    'layout' => ['about_title' => 'MediSphere के बारे में','about_text' => 'रोगियों, डॉक्टरों, अस्पतालों और एडमिन के लिए प्रीमियम हेल्थकेयर मैनेजमेंट प्लेटफ़ॉर्म।','footer_note' => 'XAMPP + PHP 8 + MySQL के लिए बनाया गया।','notifications_title' => 'नोटिफिकेशन','no_notifications' => 'अभी कोई नोटिफिकेशन नहीं है।','assistant_title' => 'हेल्थ असिस्टेंट','assistant_subtitle' => 'अपॉइंटमेंट, रिपोर्ट और सपोर्ट के बारे में पूछें','quick_book' => 'अपॉइंटमेंट कैसे बुक करें?','quick_reports' => 'रिपोर्ट कैसे अपलोड करें?','quick_emergency' => 'इमरजेंसी प्रक्रिया?'],
    'home' => ['eyebrow' => 'एआई संचालित, सुरक्षित, मल्टी-पोर्टल हेल्थकेयर इकोसिस्टम','title' => 'रोगियों, डॉक्टरों, अस्पतालों और एडमिन टीमों के लिए प्रीमियम हेल्थकेयर मैनेजमेंट।','subtitle' => 'अपॉइंटमेंट बुक करें, मेडिकल इमेज स्कैन करें, रिपोर्ट मैनेज करें और एक ही आधुनिक प्लेटफ़ॉर्म से परामर्श समन्वयित करें।','features_eyebrow' => 'प्लेटफ़ॉर्म फीचर्स','features_title' => 'पूरे केयर जर्नी को सपोर्ट करने के लिए तैयार','how_it_works' => 'यह कैसे काम करता है','how_title' => '3-स्टेप डिजिटल केयर फ्लो','featured_doctors' => 'फीचर्ड डॉक्टर','trusted_specialists' => 'विश्वसनीय विशेषज्ञ','partner_hospitals' => 'साझेदार अस्पताल','global_directory' => 'ग्लोबल हॉस्पिटल डायरेक्टरी','content_eyebrow' => 'हेल्थ कंटेंट','content_title' => 'ब्लॉग, गाइडलाइन और पेशेंट एजुकेशन','newsletter_eyebrow' => 'अपडेट रहें','newsletter_title' => 'न्यूज़लेटर साइनअप','newsletter_placeholder' => 'अपना ईमेल दर्ज करें','newsletter_note' => 'इस सेक्शन को अपनी पसंद के न्यूज़लेटर API से जोड़ें।','snapshot' => 'हेल्थ स्नैपशॉट','live' => 'लाइव','upcoming' => 'आगामी अपॉइंटमेंट','ai_scans' => 'एआई स्कैन','verified_doctors' => 'वेरिफाइड डॉक्टर','hospital_partners' => 'हॉस्पिटल पार्टनर','smart_triage' => 'स्मार्ट ट्रायज','scanner_title' => 'एआई डिज़ीज़ स्कैनर','scanner_text' => 'त्वचा, आँख या एक्स-रे इमेज अपलोड करें और परिणाम को बुकिंग व रिपोर्ट से जोड़ें।','testimonial' => 'MediSphere संचालन की जटिलता कम करता है और केयर जर्नी को सहज व सुरक्षित बनाए रखता है।','metrics' => ['specializations' => 'विशेषताएँ','support' => 'सपोर्ट चैनल','security' => 'सिक्योरिटी-रेडी स्ट्रक्चर'],'features' => require __DIR__ . '/partials/en_home_features.php','steps' => require __DIR__ . '/partials/en_home_steps.php','blogs' => ['एआई स्क्रीनिंग में कैसे मदद करता है','प्राइवेसी, HIPAA और सुरक्षित टेलीमेडिसिन','डिजिटल अपॉइंटमेंट मैनेजमेंट की सर्वोत्तम प्रथाएँ']],
    'auth' => ['eyebrow' => 'सुरक्षित प्रवेश','title' => 'अपने केयर इकोसिस्टम तक पहुँचें','subtitle' => 'रोगी, डॉक्टर या अस्पताल अकाउंट बनाएं।','login' => 'लॉग इन','patient_register' => 'रोगी रजिस्ट्रेशन','doctor_register' => 'डॉक्टर रजिस्ट्रेशन','hospital_register' => 'अस्पताल रजिस्ट्रेशन','forgot_password' => 'पासवर्ड भूल गए?','or_continue' => 'या आगे बढ़ें','send_reset' => 'रीसेट लिंक भेजें','reset_title' => 'अपना पासवर्ड रीसेट करें'],
    'faq' => ['eyebrow' => 'सपोर्ट सेंटर','title' => 'अक्सर पूछे जाने वाले सवाल','subtitle' => 'खोजने योग्य FAQ और विस्तृत उत्तर।'],
    'guidelines' => ['eyebrow' => 'गाइडलाइन','title' => 'प्लेटफ़ॉर्म उपयोग गाइडलाइन'],
    'notifications' => ['eyebrow' => 'नोटिफिकेशन सेंटर','title' => 'नोटिफिकेशन','recent' => 'हाल की सूचनाएँ','preferences' => 'पसंद','unread' => 'अनरीड'],
    'consultations' => ['eyebrow' => 'टेलीमेडिसिन','title' => 'वीडियो परामर्श','waiting_queue' => 'वेटिंग रूम कतार','eligible' => 'उपलब्ध अपॉइंटमेंट','call_history' => 'कॉल इतिहास','room_overview' => 'सेशन ओवरव्यू','waiting_room' => 'वर्चुअल वेटिंग रूम','connection_events' => 'कनेक्शन इवेंट्स','feedback' => 'परामर्श फ़ीडबैक'],
    'chatbot' => ['book_answer' => 'अपॉइंटमेंट पेज पर जाएँ, डॉक्टर, तारीख और समय चुनें और अपने लक्षण भेजें।','reports_answer' => 'रिपोर्ट पेज खोलें, श्रेणी चुनें, फ़ाइल अपलोड करें और सेव करें।','emergency_answer' => 'आपातकाल में तुरंत स्थानीय इमरजेंसी सेवा से संपर्क करें।'],
];
