<?php
return [
    'language_name' => 'اردو',
    'common' => [
        'home' => 'ہوم', 'profile' => 'پروفائل', 'appointments' => 'اپائنٹمنٹس', 'payments' => 'ادائیگیاں اور انوائسز', 'reports' => 'رپورٹس / دستاویزات', 'notifications' => 'اطلاعات', 'messages' => 'پیغامات / چیٹ', 'consultations' => 'ویڈیو مشاورت', 'scanner' => 'اے آئی اسکینر', 'map' => 'انٹرایکٹو نقشہ', 'guidelines' => 'رہنمائی', 'faq' => 'اکثر پوچھے گئے سوالات', 'verification' => 'تصدیقی مرکز', 'templates' => 'ای میل اور ایس ایم ایس ٹیمپلیٹس', 'logout' => 'لاگ آؤٹ', 'sign_in' => 'سائن اِن', 'dashboard' => 'ڈیش بورڈ', 'guest' => 'مہمان', 'public' => 'عوامی', 'view_all' => 'سب دیکھیں', 'back' => 'واپس', 'search_placeholder' => 'ڈاکٹر، ہسپتال، رپورٹس یا سوالات تلاش کریں...', 'mark_all_read' => 'سب کو پڑھا ہوا نشان زد کریں', 'save_preferences' => 'ترجیحات محفوظ کریں', 'language' => 'زبان', 'subscribe' => 'سبسکرائب', 'get_started' => 'شروع کریں', 'find_healthcare' => 'ہیلتھ کیئر تلاش کریں',
    ],
    'layout' => [
        'about_title' => 'میڈی اسفیئر کے بارے میں', 'about_text' => 'مریضوں، ڈاکٹروں، ہسپتالوں اور منتظمین کے لیے ایک پریمیم ہیلتھ کیئر پلیٹ فارم۔', 'footer_note' => 'XAMPP + PHP 8 + MySQL کے لیے تیار کردہ۔', 'notifications_title' => 'اطلاعات', 'no_notifications' => 'ابھی تک کوئی اطلاع نہیں۔', 'assistant_title' => 'ہیلتھ اسسٹنٹ', 'assistant_subtitle' => 'اپائنٹمنٹ، رپورٹس اور سپورٹ کے بارے میں پوچھیں', 'quick_book' => 'اپائنٹمنٹ کیسے بک کریں؟', 'quick_reports' => 'رپورٹس کیسے اپ لوڈ کریں؟', 'quick_emergency' => 'ایمرجنسی طریقہ کار؟',
    ],
    'home' => [
        'eyebrow' => 'اے آئی سے چلنے والا، محفوظ، ملٹی پورٹل ہیلتھ کیئر نظام', 'title' => 'مریضوں، ڈاکٹروں، ہسپتالوں اور ایڈمن ٹیموں کے لیے پریمیم ہیلتھ کیئر مینجمنٹ۔', 'subtitle' => 'اپائنٹمنٹ بک کریں، بیماری کی تصاویر اسکین کریں، رپورٹس سنبھالیں اور ایک ہی جدید پلیٹ فارم سے سب کچھ چلائیں۔', 'features_eyebrow' => 'پلیٹ فارم خصوصیات', 'features_title' => 'مکمل نگہداشت کے سفر کے لیے تیار', 'how_it_works' => 'یہ کیسے کام کرتا ہے', 'how_title' => 'آسان 3 مرحلہ ڈیجیٹل نگہداشت کا بہاؤ', 'featured_doctors' => 'نمایاں ڈاکٹر', 'trusted_specialists' => 'قابلِ اعتماد ماہرین', 'partner_hospitals' => 'شراکت دار ہسپتال', 'global_directory' => 'عالمی ہسپتال ڈائریکٹری', 'content_eyebrow' => 'صحت کا مواد', 'content_title' => 'بلاگ، رہنمائی اور مریضوں کی تعلیم', 'newsletter_eyebrow' => 'باخبر رہیں', 'newsletter_title' => 'نیوز لیٹر سائن اپ', 'newsletter_placeholder' => 'اپنا ای میل درج کریں', 'newsletter_note' => 'اس حصے کو اپنی پسند کے نیوز لیٹر API سے جوڑیں۔', 'snapshot' => 'ہیلتھ اسنیپ شاٹ', 'live' => 'لائیو', 'upcoming' => 'آنے والی اپائنٹمنٹس', 'ai_scans' => 'اے آئی اسکینز', 'verified_doctors' => 'تصدیق شدہ ڈاکٹر', 'hospital_partners' => 'شراکت دار ہسپتال', 'smart_triage' => 'سمارٹ ٹرائیج', 'scanner_title' => 'اے آئی ڈیزیز اسکینر', 'scanner_text' => 'جلد، آنکھ یا ایکس رے امیجز اپ لوڈ کریں اور نتائج کو بکنگ سے جوڑیں۔', 'testimonial' => 'میڈی اسفیئر پیچیدگی کم کرتا ہے اور نگہداشت کے سفر کو آسان بناتا ہے۔', 'metrics' => ['specializations' => 'اسپیشلائزیشنز', 'support' => 'سپورٹ چینلز', 'security' => 'سیکیورٹی تیار ساخت'],
        'features' => require __DIR__ . '/partials/en_home_features.php',
        'steps' => require __DIR__ . '/partials/en_home_steps.php',
        'blogs' => ['اے آئی اسکریننگ میں کیسے مدد کرتا ہے', 'پرائیویسی، HIPAA اور محفوظ ٹیلی میڈیسن', 'ڈیجیٹل اپائنٹمنٹ مینجمنٹ کے بہترین طریقے'],
    ],
    'auth' => ['eyebrow' => 'محفوظ رسائی', 'title' => 'اپنے ہیلتھ ایکو سسٹم تک رسائی حاصل کریں', 'subtitle' => 'مریض، ڈاکٹر یا ہسپتال اکاؤنٹ بنائیں۔', 'login' => 'لاگ اِن', 'patient_register' => 'مریض رجسٹریشن', 'doctor_register' => 'ڈاکٹر رجسٹریشن', 'hospital_register' => 'ہسپتال رجسٹریشن', 'forgot_password' => 'پاس ورڈ بھول گئے؟', 'or_continue' => 'یا جاری رکھیں', 'send_reset' => 'ری سیٹ لنک بھیجیں', 'reset_title' => 'اپنا پاس ورڈ ری سیٹ کریں'],
    'faq' => ['eyebrow' => 'سپورٹ سینٹر', 'title' => 'اکثر پوچھے گئے سوالات', 'subtitle' => 'تلاش کے قابل سوالات اور جوابات۔'],
    'guidelines' => ['eyebrow' => 'رہنمائی', 'title' => 'پلیٹ فارم استعمال کرنے کی رہنمائی'],
    'notifications' => ['eyebrow' => 'اطلاع مرکز', 'title' => 'اطلاعات', 'recent' => 'حالیہ اطلاعات', 'preferences' => 'ترجیحات', 'unread' => 'غیر پڑھی گئی'],
    'consultations' => ['eyebrow' => 'ٹیلی میڈیسن', 'title' => 'ویڈیو مشاورت', 'waiting_queue' => 'ویٹنگ روم قطار', 'eligible' => 'اہل اپائنٹمنٹس', 'call_history' => 'کال ہسٹری', 'room_overview' => 'سیشن کا جائزہ', 'waiting_room' => 'ورچوئل ویٹنگ روم', 'connection_events' => 'کنکشن ایونٹس', 'feedback' => 'مشاورت فیڈ بیک'],
    'chatbot' => ['book_answer' => 'اپائنٹمنٹس میں جائیں، ڈاکٹر، تاریخ اور وقت منتخب کریں اور علامات درج کریں۔', 'reports_answer' => 'رپورٹس کھولیں، کیٹیگری منتخب کریں، فائل اپ لوڈ کریں اور محفوظ کریں۔', 'emergency_answer' => 'فوری ضرورت میں مقامی ایمرجنسی سروس سے رابطہ کریں۔'],
];
