<?php
return [
    'language_name' => '中文',
    'common' => ['home' => '首页','profile' => '个人资料','appointments' => '预约','payments' => '支付与发票','reports' => '报告 / 文档','notifications' => '通知','messages' => '消息 / 聊天','consultations' => '视频问诊','scanner' => 'AI 扫描','map' => '互动地图','guidelines' => '指南与帮助','faq' => '常见问题','verification' => '审核中心','templates' => '邮件与短信模板','logout' => '退出登录','sign_in' => '登录','dashboard' => '仪表盘','guest' => '访客','public' => '公开','view_all' => '查看全部','back' => '返回','search_placeholder' => '搜索医生、医院、报告……','mark_all_read' => '全部标记为已读','save_preferences' => '保存偏好','language' => '语言','subscribe' => '订阅','get_started' => '开始使用','find_healthcare' => '查找医疗服务'],
    'layout' => ['about_title' => '关于 MediSphere','about_text' => '面向患者、医生、医院和管理员的高端医疗管理平台。','footer_note' => '基于 XAMPP + PHP 8 + MySQL 构建。','notifications_title' => '通知','no_notifications' => '暂无通知。','assistant_title' => '健康助手','assistant_subtitle' => '询问预约、报告和支持','quick_book' => '如何预约？','quick_reports' => '如何上传报告？','quick_emergency' => '紧急处理流程？'],
    'home' => ['eyebrow' => 'AI 驱动、安全、多门户医疗生态系统','title' => '为患者、医生、医院和管理团队打造的高端医疗管理平台。','subtitle' => '预约挂号、医学图像扫描、报告管理和远程会诊，全部在一个现代平台中完成。','features_eyebrow' => '平台功能','features_title' => '支持完整医疗服务流程','how_it_works' => '使用方式','how_title' => '三步数字化医疗流程','featured_doctors' => '精选医生','trusted_specialists' => '值得信赖的专家','partner_hospitals' => '合作医院','global_directory' => '全球医院目录','content_eyebrow' => '健康内容','content_title' => '博客、指南与患者教育','newsletter_eyebrow' => '保持更新','newsletter_title' => '订阅通讯','newsletter_placeholder' => '输入你的邮箱','newsletter_note' => '这里可接入你喜欢的邮件通讯 API。','snapshot' => '健康概览','live' => '实时','upcoming' => '即将到来的预约','ai_scans' => 'AI 扫描','verified_doctors' => '已认证医生','hospital_partners' => '合作医院','smart_triage' => '智能分诊','scanner_title' => 'AI 疾病扫描仪','scanner_text' => '上传皮肤、眼部或 X 光图像，并将结果与预约和报告流程关联。','testimonial' => 'MediSphere 降低了运营复杂度，同时保持医疗流程直观与安全。','metrics' => ['specializations' => '专科','support' => '支持渠道','security' => '安全就绪框架'],'features' => require __DIR__ . '/partials/en_home_features.php','steps' => require __DIR__ . '/partials/en_home_steps.php','blogs' => ['AI 如何支持筛查流程','隐私、HIPAA 与安全远程医疗','数字预约管理最佳实践']],
    'auth' => ['eyebrow' => '安全访问','title' => '进入你的医疗生态系统','subtitle' => '创建患者、医生或医院账户。','login' => '登录','patient_register' => '患者注册','doctor_register' => '医生注册','hospital_register' => '医院注册','forgot_password' => '忘记密码？','or_continue' => '或继续使用','send_reset' => '发送重置链接','reset_title' => '重置密码'],
    'faq' => ['eyebrow' => '支持中心','title' => '常见问题','subtitle' => '可搜索的常见问题与展开答案。'],
    'guidelines' => ['eyebrow' => '指南','title' => '平台使用指南'],
    'notifications' => ['eyebrow' => '通知中心','title' => '通知','recent' => '最新通知','preferences' => '偏好设置','unread' => '未读'],
    'consultations' => ['eyebrow' => '远程医疗','title' => '视频问诊','waiting_queue' => '等候队列','eligible' => '可用预约','call_history' => '通话历史','room_overview' => '会话概览','waiting_room' => '虚拟候诊室','connection_events' => '连接事件','feedback' => '问诊反馈'],
    'chatbot' => ['book_answer' => '进入预约页面，选择医生、日期和时间并提交症状。','reports_answer' => '打开报告页面，选择类别并上传文件后保存。','emergency_answer' => '紧急情况请立即联系当地急救服务。'],
];
