USE healthcare_platform;

INSERT IGNORE INTO disease_information
(slug, disease_name, overview, symptoms, causes, prevention, treatment, emergency_notes, status, featured_image_path, seo_title, seo_description, created_at, updated_at)
VALUES
('hypertension', 'Hypertension',
'<p>Hypertension, often called high blood pressure, means the force of blood against artery walls stays higher than recommended over time. Long-term control lowers the risk of heart attack, stroke, kidney disease, and vision problems.</p>',
'<ul><li>Often no symptoms in early stages.</li><li>Headache, dizziness, chest discomfort, or shortness of breath can occur when pressure is very high.</li><li>Some people notice nosebleeds, fatigue, or blurred vision.</li></ul>',
'<ul><li>Family history, age, high salt intake, smoking, stress, and low activity.</li><li>Diabetes, kidney disease, obesity, and sleep apnea can contribute.</li><li>Some medications may raise blood pressure.</li></ul>',
'<ul><li>Check blood pressure regularly and keep a written log.</li><li>Reduce salt, stop smoking, stay active, and sleep well.</li><li>Take prescribed medicines consistently and review side effects with a clinician.</li></ul>',
'<p>Treatment may include lifestyle changes plus medicines such as diuretics, ACE inhibitors, ARBs, calcium channel blockers, or beta blockers. Your clinician chooses based on age, other conditions, and response.</p>',
'<p>Seek urgent care for chest pain, severe headache, weakness on one side, confusion, fainting, or breathing difficulty.</p>',
'published', NULL, 'Hypertension Patient Guide', 'Symptoms, causes, prevention, and treatment notes for hypertension.', NOW(), NOW()),

('type-2-diabetes', 'Type 2 Diabetes',
'<p>Type 2 diabetes is a chronic condition where the body has trouble using insulin effectively, causing blood sugar to remain high. Early education helps prevent eye, kidney, nerve, and heart complications.</p>',
'<ul><li>Increased thirst, frequent urination, fatigue, or blurred vision.</li><li>Slow wound healing, frequent infections, or tingling in feet.</li><li>Some people have no symptoms and are diagnosed through screening.</li></ul>',
'<ul><li>Insulin resistance, family history, excess weight, low activity, and age.</li><li>History of gestational diabetes or polycystic ovary syndrome can increase risk.</li></ul>',
'<ul><li>Choose balanced meals, reduce sugary drinks, and move daily.</li><li>Screen regularly if you have risk factors.</li><li>Track blood sugar and follow medication plans when prescribed.</li></ul>',
'<p>Treatment may include nutrition support, activity, glucose monitoring, metformin, other diabetes medicines, or insulin depending on individual needs.</p>',
'<p>Seek urgent care for confusion, severe dehydration, vomiting, very high blood sugar, or symptoms of low blood sugar that do not improve quickly.</p>',
'published', NULL, 'Type 2 Diabetes Patient Guide', 'Plain-language diabetes education with symptoms, causes, prevention, and treatment notes.', NOW(), NOW()),

('asthma', 'Asthma',
'<p>Asthma is a long-term airway condition that can cause inflammation and narrowing of the breathing tubes. A written action plan helps patients know daily control steps and emergency warning signs.</p>',
'<ul><li>Wheezing, cough, chest tightness, and shortness of breath.</li><li>Symptoms may worsen at night, during exercise, or around triggers.</li><li>Severe attacks can make speaking difficult.</li></ul>',
'<ul><li>Allergies, smoke, pollution, respiratory infections, cold air, exercise, or occupational exposure.</li><li>Family history and childhood airway sensitivity can contribute.</li></ul>',
'<ul><li>Avoid known triggers and keep rescue medicine accessible.</li><li>Use controller inhalers exactly as prescribed.</li><li>Review inhaler technique and update the asthma action plan regularly.</li></ul>',
'<p>Treatment may include rescue bronchodilators, inhaled corticosteroids, combination inhalers, allergy management, or biologic medicines for severe asthma.</p>',
'<p>Seek emergency care for blue lips, severe breathlessness, confusion, or symptoms not improving after rescue medicine.</p>',
'published', NULL, 'Asthma Patient Guide', 'Asthma symptoms, triggers, prevention steps, and treatment guidance.', NOW(), NOW()),

('eczema', 'Eczema',
'<p>Eczema is an inflammatory skin condition that causes dry, itchy, irritated patches. Good skin-barrier care can reduce flare-ups and lower infection risk.</p>',
'<ul><li>Dry, itchy, red, scaly, or cracked skin.</li><li>Flare-ups may occur on hands, face, elbows, knees, or other areas.</li><li>Scratching can cause bleeding or infection.</li></ul>',
'<ul><li>Skin barrier weakness, allergies, irritants, weather changes, stress, and family history.</li><li>Fragrances, harsh soaps, and some fabrics may trigger symptoms.</li></ul>',
'<ul><li>Use fragrance-free moisturizers and gentle cleansers.</li><li>Avoid known irritants and keep nails short to reduce skin damage.</li><li>Follow clinician guidance for topical medicines.</li></ul>',
'<p>Treatment may include moisturizers, topical steroids, calcineurin inhibitors, antihistamines for itch, infection care, or advanced therapies for severe disease.</p>',
'<p>Seek care if skin becomes hot, painful, swollen, draining pus, or if fever develops.</p>',
'published', NULL, 'Eczema Patient Guide', 'Eczema symptoms, causes, prevention, and treatment overview.', NOW(), NOW()),

('migraine', 'Migraine',
'<p>Migraine is a neurological condition that can cause recurrent headache attacks and sensory symptoms. Tracking triggers and early treatment can reduce disability.</p>',
'<ul><li>Throbbing head pain, nausea, vomiting, light sensitivity, or sound sensitivity.</li><li>Some patients experience aura, visual changes, tingling, or speech difficulty.</li><li>Attacks may last hours to days.</li></ul>',
'<ul><li>Brain and nerve signaling changes, family history, stress, sleep disruption, dehydration, hormones, or certain foods.</li></ul>',
'<ul><li>Keep regular sleep, meals, hydration, and stress routines.</li><li>Track triggers in a diary.</li><li>Discuss preventive therapy if attacks are frequent or disabling.</li></ul>',
'<p>Treatment may include pain relievers, triptans, anti-nausea medicine, preventive medicines, CGRP-targeted therapies, and lifestyle planning.</p>',
'<p>Seek emergency care for the worst headache of life, new weakness, confusion, fever with stiff neck, head injury, or sudden vision loss.</p>',
'published', NULL, 'Migraine Patient Guide', 'Migraine symptoms, causes, prevention, and treatment notes.', NOW(), NOW()),

('dengue-fever', 'Dengue Fever',
'<p>Dengue fever is a mosquito-borne viral infection that can range from mild illness to severe disease. Careful hydration and warning-sign monitoring are important.</p>',
'<ul><li>High fever, severe body aches, headache, eye pain, rash, nausea, or vomiting.</li><li>Warning signs include belly pain, repeated vomiting, bleeding, drowsiness, or difficulty breathing.</li></ul>',
'<ul><li>Dengue virus spread by infected Aedes mosquitoes.</li><li>Risk increases in areas with standing water and mosquito exposure.</li></ul>',
'<ul><li>Remove standing water, use mosquito repellent, and wear protective clothing.</li><li>Use screens, nets, and community mosquito-control measures.</li></ul>',
'<p>Treatment is supportive and may include fluids, fever control, and monitoring. Avoid aspirin or ibuprofen unless a clinician advises otherwise.</p>',
'<p>Seek urgent care for bleeding, severe abdominal pain, persistent vomiting, fainting, confusion, cold hands or feet, or breathing difficulty.</p>',
'published', NULL, 'Dengue Fever Patient Guide', 'Dengue fever symptoms, causes, prevention, and warning signs.', NOW(), NOW()),

('pneumonia', 'Pneumonia',
'<p>Pneumonia is an infection that inflames the air sacs in one or both lungs. It can be mild, but older adults, infants, and patients with chronic illness can become very sick quickly.</p>',
'<ul><li>Cough, fever, chills, chest pain, fatigue, and shortness of breath.</li><li>Some patients cough up mucus or have fast breathing.</li><li>Older adults may develop confusion or weakness.</li></ul>',
'<ul><li>Bacteria, viruses, fungi, aspiration, or complications after respiratory infections.</li><li>Smoking, weak immunity, and chronic lung disease increase risk.</li></ul>',
'<ul><li>Vaccination, hand hygiene, smoking cessation, and prompt care for worsening respiratory symptoms.</li><li>Protect high-risk patients during flu and respiratory virus seasons.</li></ul>',
'<p>Treatment depends on the cause and may include antibiotics, antivirals, oxygen, fluids, rest, and hospital care for severe cases.</p>',
'<p>Seek urgent care for breathing difficulty, blue lips, chest pain, confusion, dehydration, or oxygen levels below clinician targets.</p>',
'published', NULL, 'Pneumonia Patient Guide', 'Pneumonia symptoms, causes, prevention, and treatment overview.', NOW(), NOW()),

('stroke-warning-signs', 'Stroke Warning Signs',
'<p>A stroke happens when blood flow to part of the brain is blocked or bleeding occurs in the brain. Fast action can save brain function and life.</p>',
'<ul><li>Face drooping, arm weakness, speech difficulty, sudden confusion, severe headache, vision loss, dizziness, or trouble walking.</li><li>Symptoms can be sudden and may affect one side of the body.</li></ul>',
'<ul><li>Blood clots, narrowed arteries, bleeding in the brain, hypertension, diabetes, smoking, atrial fibrillation, and high cholesterol.</li></ul>',
'<ul><li>Control blood pressure, diabetes, cholesterol, and heart rhythm problems.</li><li>Stop smoking, stay active, and take prescribed medicines consistently.</li></ul>',
'<p>Stroke treatment is time-sensitive and may include clot-busting medicine, procedures to remove clots, bleeding control, rehabilitation, and risk-factor management.</p>',
'<p>Call emergency services immediately for any stroke warning sign. Do not wait to see if symptoms go away.</p>',
'published', NULL, 'Stroke Warning Signs Patient Guide', 'Stroke warning signs, causes, prevention, and urgent care guidance.', NOW(), NOW());
