<?php
require_once __DIR__ . '/env.php';

return [
    'app' => [
        'name' => 'MediSphere',
        'base_url' => 'http://localhost/healthcare-platform/public',
        'timezone' => 'Asia/Karachi',
        'debug' => true,
        'default_route' => 'home',
        'upload_max_mb' => 10,
        'currency' => 'PKR',
        'default_locale' => 'en',
        'supported_locales' => [
            'en' => 'English',
            'ur' => 'اردو',
            'hi' => 'हिन्दी',
            'ar' => 'العربية',
            'es' => 'Español',
            'fr' => 'Français',
            'zh' => '中文',
            'de' => 'Deutsch',
        ],
        'rtl_locales' => ['ur', 'ar'],
    ],
    'db' => [
        'host' => '127.0.0.1',
        'port' => 3306,
        'database' => 'healthcare_platform',
        'username' => 'root',
        'password' => '',
        'charset' => 'utf8mb4',
    ],
    'mail' => [
        'driver' => 'mail',
        'from_email' => 'noreply@medisphere.local',
        'from_name' => 'MediSphere',
        'smtp_host' => '',
        'smtp_port' => 587,
        'smtp_user' => '',
        'smtp_pass' => '',
        'smtp_secure' => 'tls',
    ],
    'security' => [
        'session_name' => 'medisphere_session',
        'password_algo' => PASSWORD_BCRYPT,
        'max_login_attempts' => 5,
        'login_lock_minutes' => 15,
        'document_signing_key' => 'change-this-document-signing-key',
    ],
    'services' => [
        'recaptcha_site_key' => '',
        'recaptcha_secret_key' => '',
        'google_maps_key' => '',
        'twilio_sid' => '',
        'twilio_token' => '',
        'twilio_from' => '',
        'stripe_public_key' => '',
        'stripe_secret_key' => '',
        'paypal_client_id' => '',
        'paypal_client_secret' => '',
        'jazzcash_merchant_id' => '',
        'jazzcash_password' => '',
        'jazzcash_integrity_salt' => '',
        'easypaisa_store_id' => '',
        'easypaisa_hash_key' => '',
        'international_gateway' => 'verifone_2checkout',
        'subscription_settlement_account' => 'Pakistani bank, JazzCash, or Easypaisa account configured in the live gateway dashboard',
        'subscription_usd_to_pkr_rate' => 278.00,
        'verifone_2checkout_merchant_code' => '',
        'verifone_2checkout_secret_key' => '',
        'verifone_2checkout_buy_link_secret' => '',
        'verifone_2checkout_buy_link_url' => 'https://secure.2checkout.com/checkout/buy',
        'verifone_2checkout_test_mode' => true,
        'verifone_2checkout_require_ipn_hash' => true,
        'payoneer_checkout_api_base' => 'https://api.sandbox.oscato.com',
        'payoneer_checkout_username' => '',
        'payoneer_checkout_password' => '',
        'payoneer_checkout_division' => '',
        'payoneer_checkout_webhook_secret' => '',
        'google_client_id' => 'YOUR_GOOGLE_CLIENT_ID',
        'google_client_secret' => 'YOUR_GOOGLE_CLIENT_SECRET',
        'google_redirect_uri' => 'YOUR_GOOGLE_REDIRECT_URI',
        'oauth_facebook' => ['client_id' => env_value('FACEBOOK_CLIENT_ID', ''), 'client_secret' => env_value('FACEBOOK_CLIENT_SECRET', ''), 'redirect_uri' => env_value('FACEBOOK_REDIRECT_URI', '')],
        'oauth_x' => ['client_id' => env_value('X_CLIENT_ID', env_value('TWITTER_CLIENT_ID', '')), 'client_secret' => env_value('X_CLIENT_SECRET', env_value('TWITTER_CLIENT_SECRET', '')), 'redirect_uri' => env_value('X_REDIRECT_URI', env_value('TWITTER_REDIRECT_URI', ''))],
        'oauth_twitter' => ['client_id' => env_value('TWITTER_CLIENT_ID', ''), 'client_secret' => env_value('TWITTER_CLIENT_SECRET', ''), 'redirect_uri' => env_value('TWITTER_REDIRECT_URI', '')],
        'ai_model_url' => '',
        'chatbot_model_url' => '',
        'page_translator_endpoint' => env_value('PAGE_TRANSLATOR_ENDPOINT', 'https://translate.googleapis.com/translate_a/single'),
    ],
    'features' => [
        'ai_demo_mode' => true,
        'video_consultation_scaffold' => true,
        'payments_scaffold' => true,
        'subscription_payments' => true,
        'mock_payments' => true,
        'social_login_scaffold' => true,
        'page_translator_remote' => true,
        'qa_premium_emails' => ['ASDF1223@gmail.com'],
    ],
];
