<?php
require_once __DIR__ . '/env.php';

return [
    'app' => [
        'name' => 'MediSphere',
        'base_url' => env_value('APP_BASE_URL', 'http://localhost/healthcare-platform/public'),
        'timezone' => env_value('APP_TIMEZONE', 'Asia/Karachi'),
        'debug' => env_value('APP_DEBUG', 'false') === 'true',
        'default_route' => 'home',
        'upload_max_mb' => 10,
        'currency' => 'PKR',
        'default_locale' => 'en',
        'supported_locales' => [
            'en' => 'English',
            'ur' => 'اردو',
            'hi' => 'हिन्दी',
            'ar' => 'العربية',
            'es' => 'Español',
            'fr' => 'Français',
            'zh' => '中文',
            'de' => 'Deutsch',
        ],
        'rtl_locales' => ['ur', 'ar'],
    ],
    'db' => [
        'host' => env_value('DB_HOST', '127.0.0.1'),
        'port' => (int) env_value('DB_PORT', '3306'),
        'database' => env_value('DB_DATABASE', 'healthcare_platform'),
        'username' => env_value('DB_USERNAME', 'root'),
        'password' => env_value('DB_PASSWORD', ''),
        'charset' => 'utf8mb4',
    ],
    'mail' => [
        'driver' => env_value('MAIL_DRIVER', 'mail'),
        'from_email' => env_value('MAIL_FROM_EMAIL', 'noreply@medisphere.local'),
        'from_name' => env_value('MAIL_FROM_NAME', 'MediSphere'),
        'smtp_host' => env_value('MAIL_SMTP_HOST', ''),
        'smtp_port' => (int) env_value('MAIL_SMTP_PORT', '587'),
        'smtp_user' => env_value('MAIL_SMTP_USER', ''),
        'smtp_pass' => env_value('MAIL_SMTP_PASS', ''),
        'smtp_secure' => env_value('MAIL_SMTP_SECURE', 'tls'),
    ],
    'security' => [
        'session_name' => env_value('SESSION_NAME', 'medisphere_session'),
        'password_algo' => PASSWORD_BCRYPT,
        'max_login_attempts' => (int) env_value('MAX_LOGIN_ATTEMPTS', '5'),
        'login_lock_minutes' => (int) env_value('LOGIN_LOCK_MINUTES', '15'),
        'document_signing_key' => env_value('DOCUMENT_SIGNING_KEY', 'change-this-document-signing-key'),
    ],
    'services' => [
        'recaptcha_site_key' => env_value('RECAPTCHA_SITE_KEY', ''),
        'recaptcha_secret_key' => env_value('RECAPTCHA_SECRET_KEY', ''),
        'google_maps_key' => env_value('GOOGLE_MAPS_KEY', ''),
        'twilio_sid' => env_value('TWILIO_SID', ''),
        'twilio_token' => env_value('TWILIO_TOKEN', ''),
        'twilio_from' => env_value('TWILIO_FROM', ''),
        'stripe_public_key' => env_value('STRIPE_PUBLIC_KEY', ''),
        'stripe_secret_key' => env_value('STRIPE_SECRET_KEY', ''),
        'paypal_client_id' => env_value('PAYPAL_CLIENT_ID', ''),
        'paypal_client_secret' => env_value('PAYPAL_CLIENT_SECRET', ''),
        'jazzcash_merchant_id' => env_value('JAZZCASH_MERCHANT_ID', ''),
        'jazzcash_password' => env_value('JAZZCASH_PASSWORD', ''),
        'jazzcash_integrity_salt' => env_value('JAZZCASH_INTEGRITY_SALT', ''),
        'easypaisa_store_id' => env_value('EASYPAISA_STORE_ID', ''),
        'easypaisa_hash_key' => env_value('EASYPAISA_HASH_KEY', ''),
        'international_gateway' => env_value('INTERNATIONAL_GATEWAY', 'verifone_2checkout'),
        'subscription_settlement_account' => env_value('SUBSCRIPTION_SETTLEMENT_ACCOUNT', 'Pakistani bank, JazzCash, or Easypaisa account configured in the live gateway dashboard'),
        'subscription_usd_to_pkr_rate' => (float) env_value('SUBSCRIPTION_USD_TO_PKR_RATE', '278.00'),
        'verifone_2checkout_merchant_code' => env_value('VERIFONE_2CHECKOUT_MERCHANT_CODE', ''),
        'verifone_2checkout_secret_key' => env_value('VERIFONE_2CHECKOUT_SECRET_KEY', ''),
        'verifone_2checkout_buy_link_secret' => env_value('VERIFONE_2CHECKOUT_BUY_LINK_SECRET', ''),
        'verifone_2checkout_buy_link_url' => env_value('VERIFONE_2CHECKOUT_BUY_LINK_URL', 'https://secure.2checkout.com/checkout/buy'),
        'verifone_2checkout_test_mode' => env_value('VERIFONE_2CHECKOUT_TEST_MODE', 'true') === 'true',
        'verifone_2checkout_require_ipn_hash' => env_value('VERIFONE_2CHECKOUT_REQUIRE_IPN_HASH', 'true') === 'true',
        'payoneer_checkout_api_base' => env_value('PAYONEER_CHECKOUT_API_BASE', 'https://api.sandbox.oscato.com'),
        'payoneer_checkout_username' => env_value('PAYONEER_CHECKOUT_USERNAME', ''),
        'payoneer_checkout_password' => env_value('PAYONEER_CHECKOUT_PASSWORD', ''),
        'payoneer_checkout_division' => env_value('PAYONEER_CHECKOUT_DIVISION', ''),
        'payoneer_checkout_webhook_secret' => env_value('PAYONEER_CHECKOUT_WEBHOOK_SECRET', ''),
        'oauth_google' => ['client_id' => env_value('GOOGLE_CLIENT_ID', ''), 'client_secret' => env_value('GOOGLE_CLIENT_SECRET', ''), 'redirect_uri' => env_value('GOOGLE_REDIRECT_URI', '')],
        'oauth_facebook' => ['client_id' => env_value('FACEBOOK_CLIENT_ID', ''), 'client_secret' => env_value('FACEBOOK_CLIENT_SECRET', ''), 'redirect_uri' => env_value('FACEBOOK_REDIRECT_URI', '')],
        'oauth_x' => ['client_id' => env_value('X_CLIENT_ID', env_value('TWITTER_CLIENT_ID', '')), 'client_secret' => env_value('X_CLIENT_SECRET', env_value('TWITTER_CLIENT_SECRET', '')), 'redirect_uri' => env_value('X_REDIRECT_URI', env_value('TWITTER_REDIRECT_URI', ''))],
        'oauth_twitter' => ['client_id' => env_value('TWITTER_CLIENT_ID', ''), 'client_secret' => env_value('TWITTER_CLIENT_SECRET', ''), 'redirect_uri' => env_value('TWITTER_REDIRECT_URI', '')],
        'ai_model_url' => env_value('AI_MODEL_URL', ''),
        'chatbot_model_url' => env_value('CHATBOT_MODEL_URL', ''),
        'page_translator_endpoint' => env_value('PAGE_TRANSLATOR_ENDPOINT', 'https://translate.googleapis.com/translate_a/single'),
    ],
    'features' => [
        'ai_demo_mode' => true,
        'video_consultation_scaffold' => true,
        'payments_scaffold' => true,
        'subscription_payments' => true,
        'mock_payments' => true,
        'social_login_scaffold' => true,
        'page_translator_remote' => true,
        'qa_premium_emails' => ['ASDF1223@gmail.com'],
    ],
];
